In [1]:
conda install pytorch torchvision torchaudio -c pytorch

Solving environment: - 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/noarch::holoviews==1.14.8=pyhd3eb1b0_0
  - defaults/osx-64::notebook==6.4.8=py39hecd8cb5_0
  - defaults/noarch::nbclassic==0.3.5=pyhd3eb1b0_0
  - defaults/osx-64::jupyter==1.0.0=py39hecd8cb5_7
  - defaults/noarch::cookiecutter==1.7.3=pyhd3eb1b0_0
  - defaults/noarch::dask==2022.2.1=pyhd3eb1b0_0
  - defaults/osx-64::anaconda==2022.05=py39_0
  - defaults/noarch::datashader==0.13.0=pyhd3eb1b0_1
  - defaults/noarch::jupyter_server==1.13.5=pyhd3eb1b0_0
  - defaults/osx-64::conda-build==3.21.8=py39hecd8cb5_2
  - defaults/noarch::sphinx==4.4.0=pyhd3eb1b0_0
  - defaults/noarch::numpydoc==1.2=pyhd3eb1b0_0
  - defaults/noarch::anaconda-project==0.10.2=pyhd3eb1b0_0
  - defaults/osx-64::_ipyw_jlab_nb_ext_conf==0.1.0=py39hecd8cb5_1
  - defaults/noarch::conda-verify==3.4.2=py_1
  - defaults/noarch::jinja2-time==0.2.0=pyhd3eb1b0_3
  - def

In [1]:
import torch

In [2]:
z = torch.zeros(5,3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


#### Above we created 5x3 matrix filled with zeros and query its datatype to find out that the zeros are 32-bit floating point numbers which is default pytorch what if you wanted integers instead you can always override it

In [3]:
i = torch.ones((5,3),dtype =torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


#### When we do change the default the tensor helpfully reports when printed 

its is common to initialize learning weights randomly, often with specific seed for the PRNG for reproducibility of results 

In [4]:
torch.manual_seed(1729)
r1= torch.rand(2, 2)
print('A random tensor:')
print(r1)

r2= torch.rand(2, 2)
print('\nA different random tensor:')
print(r2)

torch.manual_seed(1729)
r3= torch.rand(2, 2)
print('\n Should match r1:')
print(r3)

A random tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

A different random tensor:
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])

 Should match r1:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


#### Pytorch tensor performs Arithmetic operations intuitively, Thensor of similar shapes maybe, added Multiplied, etc. Operations with scalars are distributed over the tensor:

In [5]:
ones = torch.ones(2, 3)
print(ones)

twos = torch.ones(2,3) * 2
print(twos)

threes = ones + twos 
print(threes)
print(threes.shape)

r1 = torch.rand(2, 3)
r2 = torch.rand(3, 2)
r3 = r1 + r2

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

there is no way to do aritmetic operations with two sensors without getting a runtime error, hence the error on the top

In [9]:
r = torch.rand(2,2) - 0.5 * 2 # Values btw -1 and 1
print('A random matrix, r:')
print(r)

print('\n Absolute value of r:')
print(torch.abs(r))

print('\n Inverse sine of r:')
print(torch.asin(r))

print('\n Determinant of r:')
print(torch.det(r))
print('\n Singular value decomposition of r:')
print(torch.svd(r))

print('\n Average and standard deviation of r:')
print(torch.std_mean(r))
print('\n Maximum value of r:')
print(torch.max(r))

A random matrix, r:
tensor([[-0.0022, -0.6116],
        [-0.3071, -0.8297]])

 Absolute value of r:
tensor([[0.0022, 0.6116],
        [0.3071, 0.8297]])

 Inverse sine of r:
tensor([[-0.0022, -0.6581],
        [-0.3122, -0.9785]])

 Determinant of r:
tensor(-0.1860)

 Singular value decomposition of r:
torch.return_types.svd(
U=tensor([[-0.5599, -0.8286],
        [-0.8286,  0.5599]]),
S=tensor([1.0611, 0.1753]),
V=tensor([[ 0.2410, -0.9705],
        [ 0.9705,  0.2410]]))

 Average and standard deviation of r:
(tensor(0.3608), tensor(-0.4376))

 Maximum value of r:
tensor(-0.0022)
